# -*- python -*-

import lsst.sconsUtils
import os

# scons steals our environment away, so we have to reinstate it
env = lsst.sconsUtils.env.Clone()
for name in ("PYTHONPATH", "LD_LIBRARY_PATH", "DYLD_LIBRARY_PATH", "PATH"):
    if name in os.environ:
        env.AppendENVPath(name, os.environ[name])

env.AlwaysBuild(env.Command(["camera/1.fits", "camera/2.fits", "camera/3.fits", "camera/4.fits"],
                            "#bin/makeCasuWfcam.py", "bin/makeCasuWfcam.py"))
